package com.nemesis.rio.domain.profile.character.attributes

enum class Spec(val role: Role) {
    // Warlock
    AFFLICTION(Role.DAMAGE_DEALER), DESTRUCTION(Role.DAMAGE_DEALER), DEMONOLOGY(Role.DAMAGE_DEALER),

    // Rogue
    ASSASSINATION(Role.DAMAGE_DEALER), SUBTLETY(Role.DAMAGE_DEALER), OUTLAW(Role.DAMAGE_DEALER),

    // Demon Hunter
    HAVOC(Role.DAMAGE_DEALER), VENGEANCE(Role.TANK),

    // Warrior
    PROTECTION_WARRIOR(Role.TANK), ARMS(Role.DAMAGE_DEALER), FURY(Role.DAMAGE_DEALER),

    // Mage
    FROST_MAGE(Role.DAMAGE_DEALER), FIRE(Role.DAMAGE_DEALER), ARCANE(Role.DAMAGE_DEALER),

    // Death Knight
    FROST_DEATH_KNIGHT(Role.DAMAGE_DEALER), BLOOD(Role.TANK), UNHOLY(Role.DAMAGE_DEALER),

    // Priest
    HOLY_PRIEST(Role.HEALER), DISCIPLINE(Role.HEALER), SHADOW(Role.DAMAGE_DEALER),

    // Druid
    RESTORATION_DRUID(Role.HEALER), GUARDIAN(Role.TANK), FERAL(Role.DAMAGE_DEALER), BALANCE(Role.DAMAGE_DEALER),

    // Monk
    BREWMASTER(Role.TANK), WINDWALKER(Role.DAMAGE_DEALER), MISTWEAVER(Role.HEALER),

    // Shaman
    RESTORATION_SHAMAN(Role.HEALER), ELEMENTAL(Role.DAMAGE_DEALER), ENHANCEMENT(Role.DAMAGE_DEALER),

    // Hunter
    BEAST_MASTERY(Role.DAMAGE_DEALER), MARKSMANSHIP(Role.DAMAGE_DEALER), SURVIVAL(Role.DAMAGE_DEALER),

    // Paladin
    PROTECTION_PALADIN(Role.TANK), RETRIBUTION(Role.DAMAGE_DEALER), HOLY_PALADIN(Role.HEALER)
}
